In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('/content/AB_NYC_2019.csv')

In [ ]:
df.head()

id                                              name  host_id  \
0  2539                Clean & quiet apt home by the park     2787   
1  2595                             Skylit Midtown Castle     2845   
2  3647               THE VILLAGE OF HARLEM....NEW YORK !     4632   
3  3831                   Cozy Entire Floor of Brownstone     4869   
4  5022  Entire Apt: Spacious Studio/Loft by central park     7192   

     host_name neighbourhood_group neighbourhood  latitude  longitude  \
0         John            Brooklyn    Kensington  40.64749  -73.97237   
1     Jennifer           Manhattan       Midtown  40.75362  -73.98377   
2    Elisabeth           Manhattan        Harlem  40.80902  -73.94190   
3  LisaRoxanne            Brooklyn  Clinton Hill  40.68514  -73.95976   
4        Laura           Manhattan   East Harlem  40.79851  -73.94399   

         room_type  price  minimum_nights  number_of_reviews last_review  \
0     Private room    149               1                  9  2018-10-19   
1  Entire home/apt    225               1                 45  2019-05-21   
2     Private room    150               3                  0         NaN   
3  Entire home/apt     89               1                270  2019-07-05   
4  Entire home/apt     80              10                  9  2018-11-19   

   reviews_per_month  calculated_host_listings_count  availability_365  
0               0.21                               6               365  
1               0.38                               2               355  
2                NaN                               1               365  
3               4.64                               1               194  
4               0.10                               1                 0

In [ ]:
neighbourhood_group = pd.get_dummies(df['neighbourhood_group'], drop_first = True)
neighbourhood_group.head()

Brooklyn  Manhattan  Queens  Staten Island
0         1          0       0              0
1         0          1       0              0
2         0          1       0              0
3         1          0       0              0
4         0          1       0              0

In [ ]:
df['room_type'].nunique()

3

In [ ]:
room_type_group = pd.get_dummies(df['room_type'], drop_first = True)
room_type_group.head()

Private room  Shared room
0             1            0
1             0            0
2             1            0
3             0            0
4             0            0

In [ ]:
df = pd.concat([df, neighbourhood_group, room_type_group], axis = 1)
df.head(3)

id                                 name  host_id  host_name  \
0  2539   Clean & quiet apt home by the park     2787       John   
1  2595                Skylit Midtown Castle     2845   Jennifer   
2  3647  THE VILLAGE OF HARLEM....NEW YORK !     4632  Elisabeth   

  neighbourhood_group neighbourhood  latitude  longitude        room_type  \
0            Brooklyn    Kensington  40.64749  -73.97237     Private room   
1           Manhattan       Midtown  40.75362  -73.98377  Entire home/apt   
2           Manhattan        Harlem  40.80902  -73.94190     Private room   

   price  ...  last_review  reviews_per_month calculated_host_listings_count  \
0    149  ...   2018-10-19               0.21                              6   
1    225  ...   2019-05-21               0.38                              2   
2    150  ...          NaN                NaN                              1   

   availability_365  Brooklyn  Manhattan  Queens  Staten Island  Private room  \
0               365         1          0       0              0             1   
1               355         0          1       0              0             0   
2               365         0          1       0              0             1   

   Shared room  
0            0  
1            0  
2            0  

[3 rows x 22 columns]

In [ ]:
df.isna().sum()

id                                    0
name                                 16
host_id                               0
host_name                            21
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       10052
reviews_per_month                 10052
calculated_host_listings_count        0
availability_365                      0
Brooklyn                              0
Manhattan                             0
Queens                                0
Staten Island                         0
Private room                          0
Shared room                           0
dtype: int64

In [ ]:
df['reviews_per_month'].fillna(0, inplace=True)

In [ ]:
df.isna().sum()

id                                    0
name                                 16
host_id                               0
host_name                            21
neighbourhood_group                   0
neighbourhood                         0
latitude                              0
longitude                             0
room_type                             0
price                                 0
minimum_nights                        0
number_of_reviews                     0
last_review                       10052
reviews_per_month                     0
calculated_host_listings_count        0
availability_365                      0
Brooklyn                              0
Manhattan                             0
Queens                                0
Staten Island                         0
Private room                          0
Shared room                           0
dtype: int64

In [ ]:
df.drop(['id', 'host_id','neighbourhood_group','name','host_name', 'availability_365','neighbourhood','room_type','last_review'], axis=1, inplace=True)
df.head(3)

latitude  longitude  price  minimum_nights  number_of_reviews  \
0  40.64749  -73.97237    149               1                  9   
1  40.75362  -73.98377    225               1                 45   
2  40.80902  -73.94190    150               3                  0   

   reviews_per_month  calculated_host_listings_count  Brooklyn  Manhattan  \
0               0.21                               6         1          0   
1               0.38                               2         0          1   
2               0.00                               1         0          1   

   Queens  Staten Island  Private room  Shared room  
0       0              0             1            0  
1       0              0             0            0  
2       0              0             1            0

In [ ]:
X = df.drop('price', axis=1)

y = df['price']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=101)

In [ ]:
from sklearn.svm import SVC

In [ ]:
model = SVC()

In [ ]:
model.fit(X_train,y_train)

SVC()

In [ ]:
predictions = model.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix

In [ ]:
print(confusion_matrix(y_test,predictions))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         3
          10       0.00      0.00      0.00         3
          12       0.00      0.00      0.00         1
          15       0.00      0.00      0.00         1
          18       0.00      0.00      0.00         1
          20       0.00      0.00      0.00         8
          21       0.00      0.00      0.00         3
          22       0.00      0.00      0.00         2
          24       0.00      0.00      0.00         1
          25       0.00      0.00      0.00        12
          26       0.00      0.00      0.00         6
          27       0.00      0.00      0.00         3
          28       0.00      0.00      0.00         8
          29       0.00      0.00      0.00        13
          30       0.00      0.00      0.00        58
          31       0.00      0.00      0.00        10
          32       0.00      0.00      0.00        17
          33       0.00    

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
param_grid = {'C': [0.1,1, 10, 100, 1000], 'gamma': [1,0.1,0.01,0.001,0.0001], 'kernel': ['rbf']}

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
grid = GridSearchCV(SVC(),param_grid,refit=True,verbose=3)

In [ ]:
grid.fit(X_train,y_train)

In [ ]:
grid.best_params_

In [ ]:
grid.best_estimator_

In [ ]:
grid_predictions = grid.predict(X_test)

In [ ]:
print(confusion_matrix(y_test,grid_predictions))

In [ ]:
print(classification_report(y_test,grid_predictions))

In [ ]:
plt.scatter(y_test, predictions)
plt.xlabel('y_test')
plt.ylabel('predictions')

In [ ]:
sns.distplot((y_test-predictions),bins=50)